# Generated by Django 5.0.1 on 2024-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_Number', models.IntegerField()),
                ('emp_name', models.CharField(max_length=60)),
                ('emp_salary', models.FloatField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_address', models.CharField(max_length=165)),
            ],
        ),
    ]
