# Generated by Django 5.0.1 on 2024-02-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_Number',
            new_name='emp_number',
        ),
    ]
